export const structures = [
  {
    id: 1,
    headText: "Struktur2",
    structureText: "structure-text",
    structureOne: "structure-one",
    structureTwo: "structure-two",
    structureThree: "structure-three",
    structureFour: "structure-four",
    imgIcon: "img-icon",
    text: "text",
    one: "one",
    two: "two",
    three: "three",
    four: "four",
    isShown: false,
  },
  {
    id: 2,
    headText: "Struktur3",
    structureText: "structure-text",
    structureOne: "structure-one",
    structureTwo: "structure-two",
    structureThree: "structure-three",
    structureFour: "structure-four",
    imgIcon: "img-icon",
    text: "text",
    one: "one",
    two: "two",
    three: "three",
    four: "four",
    isShown: false,
  },
  {
    id: 3,
    headText: "Struktur4",
    structureText: "structure-text",
    structureOne: "structure-one",
    structureTwo: "structure-two",
    structureThree: "structure-three",
    structureFour: "structure-four",
    imgIcon: "img-icon",
    text: "text",
    one: "one",
    two: "two",
    three: "three",
    four: "four",
    isShown: false,
  },
  {
    id: 4,
    headText: "Struktur5",
    structureText: "structure-text",
    structureOne: "structure-one",
    structureTwo: "structure-two",
    structureThree: "structure-three",
    structureFour: "structure-four",
    imgIcon: "img-icon",
    text: "text",
    one: "one",
    two: "two",
    three: "three",
    four: "four",
    isShown: true,
  },
  {
    id: 5,
    headText: "Struktur6",
    structureText: "structure-text",
    structureOne: "structure-one",
    structureTwo: "structure-two",
    structureThree: "structure-three",
    structureFour: "structure-four",
    imgIcon: "img-icon",
    text: "text",
    one: "one",
    two: "two",
    three: "three",
    four: "four",
    isShown: false,
  },
  {
    id: 6,
    headText: "Struktur7",
    structureText: "structure-text",
    structureOne: "structure-one",
    structureTwo: "structure-two",
    structureThree: "structure-three",
    structureFour: "structure-four",
    imgIcon: "img-icon",
    text: "text",
    one: "one",
    two: "two",
    three: "three",
    four: "four",
    isShown: false,
  },
  {
    id: 7,
    headText: "Struktur8",
    structureText: "structure-text",
    structureOne: "structure-one",
    structureTwo: "structure-two",
    structureThree: "structure-three",
    structureFour: "structure-four",
    imgIcon: "img-icon",
    text: "text",
    one: "one",
    two: "two",
    three: "three",
    four: "four",
    isShown: false,
  },
  {
    id: 8,
    headText: "Struktur9",
    structureText: "structure-text",
    structureOne: "structure-one",
    structureTwo: "structure-two",
    structureThree: "structure-three",
    structureFour: "structure-four",
    imgIcon: "img-icon",
    text: "text",
    one: "one",
    two: "two",
    three: "three",
    four: "four",
    isShown: false,
  },
  {
    id: 9,
    headText: "Struktur10",
    structureText: "structure-text",
    structureOne: "structure-one",
    structureTwo: "structure-two",
    structureThree: "structure-three",
    structureFour: "structure-four",
    imgIcon: "img-icon",
    text: "text",
    one: "one",
    two: "two",
    three: "three",
    four: "four",
    isShown: false,
  },
  {
    id: 10,
    headText: "Struktur11",
    structureText: "structure-text",
    structureOne: "structure-one",
    structureTwo: "structure-two",
    structureThree: "structure-three",
    structureFour: "structure-four",
    imgIcon: "img-icon",
    text: "text",
    one: "one",
    two: "two",
    three: "three",
    four: "four",
    isShown: false,
  },
  {
    id: 11,
    headText: "Struktur12",
    structureText: "structure-text",
    structureOne: "structure-one",
    structureTwo: "structure-two",
    structureThree: "structure-three",
    structureFour: "structure-four",
    imgIcon: "img-icon",
    text: "text",
    one: "one",
    two: "two",
    three: "three",
    four: "four",
    isShown: false,
  },
  {
    id: 12,
    headText: "Struktur13",
    structureText: "structure-text",
    structureOne: "structure-one",
    structureTwo: "structure-two",
    structureThree: "structure-three",
    structureFour: "structure-four",
    imgIcon: "img-icon",
    text: "text",
    one: "one",
    two: "two",
    three: "three",
    four: "four",
    isShown: false,
  },
];
